stages:
  - build
  - test

before_script:
 - echo "Before script section"
 - RUN microdnf install findutils

build:
  stage: build
  script:
    - cd spotforus/
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd spotforus/
    - ./gradlew test
    - ./gradlew.bat --stop
