stages:
  # - build
  # - test
  # - sonarqube-analysis
  - docker

# build:
#   stage: build
#   script:
#     - cd spotforus/
#     - ./gradlew build -x test
#     - ./gradlew --stop

# test:
#   stage: test
#   script:
#     - cd spotforus/
#     - ./gradlew test
#     - ./gradlew --stop

# sonarqube-check:
#   stage: sonarqube-analysis
#   image: gradle:latest
#   variables:
#     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
#     GIT_DEPTH: "0"
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script: 
#     - cd spotforus
#     - gradle build jacocoTestReport sonar
#   allow_failure: true
#   only:
#     - main

docker:
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:latest-dind
  stage: docker
  script:
      - docker info
